config/routes.rb
require 'sidekiq/web'

Liveinbham::Application.routes.draw do
	root :to => "home#index"

	get "administrator/index", :as => "admin"
	devise_for :users, :controllers => {:registrations => "registrations"}

	resources :users
	resources :buildings
	resources :categories
	resources :zip_codes
	resources :units

	namespace :api, defaults: {format: 'json'} do
	    namespace :v1 do
	    	resources :units
	    	resources :categories
	    	get "featured", to: 'units#featured'
	    	get "viewer", to: 'units#viewer'
	    end
	end
	authenticate :user, lambda{ |u| u.has_role? :admin } do
		mount Sidekiq::Web, at: '/sidekiq'
	end
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @buildings = Building.all
    @zip_codes = ZipCode.all
    @users = User.all
    @units = Unit.all
    @keys = ApiKey.all
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/views/administrator/index.html.erb
<h3>Administration Portal</h1>

<dl class="tabs" data-tab>
  <dd class="active"><a href="#unitsPanel">Units</a></dd>
  <dd><a href="#buildingsPanel">Buildings</a></dd>
  <dd><a href="#zipsPanel">Zip Codes</a></dd>
  <dd><a href="#usersPanel">Users</a></dd>
</dl>

<div class="tabs-content">
  <div class="content active" id="unitsPanel">
    <table>
      <thead>
        <tr>
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin && @units.length == 0 %>
              <th></th>
            <% end %>
          <% end %>
          <th>Number</th>
          <th>Availability Date</th>
          <th>Category</th>
          <th>Building</th>
          <th>Title</th>
          <th>Bedrooms</th>
          <th>Bathrooms</th>
          <th>Price Per Month</th>
          <th>Contact Phone Number</th>
          <% unless @units.length == 0 %><th></th><% end %>
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin && @units.length == 0 %>
              <th></th>
              <th></th>
            <% end %>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @units.each do |unit| %>
          <tr>
            <% if user_signed_in? %>
              <% if current_user.has_role? :admin && @units.length == 0 %>
                <td>
                  <% if unit.featured? %>
                    <%= link_to fa_icon("star lg"), "#", id: unit.id, class: "featured_on", remote: true %>
                  <% else %>
                    <%= link_to fa_icon("star-o lg"), "#", id: unit.id, class: "featured_off", remote: true %>
                  <% end %>
                </td>
              <% end %>
            <% end %>
            <td><%= unit.number %></td>
            <td><%= unit.avail_date.strftime("%a, %b %e") %></td>
            <td><%= unit.category.name %></td>
            <td><%= unit.building.name %></td>
            <td><%= unit.title %></td>
            <td><%= unit.bedrooms %></td>
            <td><%= unit.bathrooms %></td>
            <td><%= number_to_currency(unit.price) %></td>
            <td><%= unit.phoneNum %></td>
            <td><%= link_to 'More Information', unit %></td>
            <% if user_signed_in? %>
              <% if current_user.has_role? :admin %>
                <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
                <td><%= link_to 'Delete', unit, method: "delete", confirm: 'Are you sure?', remote: true, class: "delete_unit" %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
        <%= link_to 'New Unit', new_unit_path, class: "button small success radius" %>
      <% end %>
    <% end %>
  </div>
  <div class="content" id="buildingsPanel">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Zip code</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @buildings.each do |building| %>
          <tr>
            <td><%= link_to building.name, building %></td>
            <td><%= building.address %></td>
            <td><%= building.city %></td>
            <td><%= building.state %></td>
            <td><%= building.zip_code.zip_code %></td>
            <td><%= link_to 'Edit', edit_building_path(building) %></td>
            <td><%= link_to 'Delete', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Building', new_building_path, class: "button small success radius" %>
  </div>
  <div class="content" id="zipsPanel">
    <table>
      <thead>
        <tr>
          <th>Zip Code</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @zip_codes.each do |zip_code| %>
          <tr>
            <td><%= link_to zip_code.zip_code, zip_code %></td>
            <td><%= link_to 'Edit', edit_zip_code_path(zip_code) %></td>
            <td><%= link_to 'Delete', zip_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Zip Code', new_zip_code_path, class: "button small success radius" %>
  </div>
  <div class="content" id="usersPanel">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.to_date %></td>
          <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
          <td>
            <a href="#" data-reveal-id="role-options-<%= user.id %>" class="button tiny radius" type="button">Change role</a>
            <%= render "users/user", :user => user %>
          </td>
          <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button tiny alert radius') unless user == current_user %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% if user_signed_in? %>
      <% if current_user.has_role? :super %>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Access Token</th>
            </tr>
          </thead>
          <tbody>
            <% @keys.each do |key| %>
            <tr>
              <td><%= key.access_token %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
  </div>
</div>