config/routes.rb
require 'sidekiq/web'

Liveinbham::Application.routes.draw do
	root :to => "home#index"

	get "administrator/index", :as => "admin"
	devise_for :users, :controllers => {:registrations => "registrations"}

	resources :users
	resources :buildings
	resources :categories
	resources :zip_codes
	resources :units

	namespace :api, defaults: {format: 'json'} do
	    namespace :v1 do
	    	resources :units
	    	resources :categories
	    	get "featured", to: 'units#featured'
	    	get "viewer", to: 'units#viewer'
	    end
	end
	authenticate :user, lambda{ |u| u.has_role? :admin } do
		mount Sidekiq::Web, at: '/sidekiq'
	end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  before_create :set_featured
  after_destroy :delete_image

  belongs_to :category
  belongs_to :building

  mount_uploader :image, ImageUploader
  process_in_background :image
  store_in_background :image

  scope :featured, -> { where(featured: 1) }

  validates_presence_of :number, :avail_date, :category, :building, :title, :description, :bedrooms, :bathrooms, :price

  def set_featured 
  	self.featured = 0
  end
  def delete_image
    self.remove_image!
  end
end

app/controllers/api/v1/units_controller.rb
module Api
	module V1
		class UnitsController < ApplicationController
			before_filter :restrict_access
			respond_to :json

			def index
				@units = Unit.all
				respond_with { @units }
			end

			def featured
				@units = Unit.featured.all
				respond_with { @units }
			end
			def viewer
				@units = Unit.all
				respond_with { @units }
			end

		private
			def restrict_access
				api_key = ApiKey.find_by_access_token(params[:access_token])
				head :unauthorized unless api_key
			end
		    # Use callbacks to share common setup or constraints between actions.
		    def set_unit
		      @unit = Unit.find(params[:id])
		    end
		    # Never trust parameters from the scary internet, only allow the white list through.
		    def unit_params
		      params.require(:unit).permit(:featured, :number, :avail_date, :title, :description, :bedrooms, :bathrooms, :price, :link, :image)
		    end
		end
	end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @units = Unit.all
  end

  def show
  end

  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @unit = Unit.new
  end

  def edit
    authorize! :edit, @user, :message => 'Not authorized as an administrator.'
  end

  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
      format.js { render :nothing => true }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:featured, :number, :avail_date, :category_id, :building_id, :title, :description, :bedrooms, :bathrooms, :price, :link, :image, :phoneNum)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= simple_form_for(@unit) do |f| %>
  <%= f.error_notification %>
  
  <%= f.input :number, label: "Unit Number" %>
  <%= f.input :avail_date, label: "Availability Date", input_html: { id: "availDate" }, as: :string %>
  <%= f.association :category %>
  <%= f.association :building %>
  <%= f.input :title, label: "Listing Title" %>
  <%= f.input :description %>
  <%= f.input :bedrooms, label: "Number of Bedrooms", as: :string %>
  <%= f.input :bathrooms, label: "Number of Bathrooms", as: :string %>
  <%= f.input :price, label:"Price Per Month", as: :string %>
  <%= f.input :phoneNum, label: "Contact Phone Number", :hint => "Format: (XXX) XXX-XXXX" %>
  <%= f.input :link %>
  <%= f.input :image, :hint => "Optimal size is 640x380px" %>
    
  <%= f.button :submit, class: "button small radius" %>
<% end %>

app/views/units/edit.html.erb
<h1>Edit Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h3>All Units</h3>

<table>
  <thead>
    <tr>
      <% if user_signed_in? %>
        <% if current_user.has_role? :admin && @units.length == 0 %>
          <th></th>
        <% end %>
      <% end %>
      <th>Number</th>
      <th>Availability Date</th>
      <th>Category</th>
      <th>Building</th>
      <th>Title</th>
      <th>Bedrooms</th>
      <th>Bathrooms</th>
      <th>Price Per Month</th>
      <th>Contact Phone Number</th>
      <%#<th>Image</th>%>
      <% unless @units.length == 0 %><th></th><% end %>
      <% if user_signed_in? %>
        <% if current_user.has_role? :admin && @units.length == 0 %>
          <th></th>
          <th></th>
        <% end %>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <% if user_signed_in? %>
          <% if current_user.has_role? :admin && @units.length == 0 %>
            <td>
              <% if unit.featured? %>
                <%= link_to fa_icon("star lg"), "#", id: unit.id, class: "featured_on", remote: true %>
              <% else %>
                <%= link_to fa_icon("star-o lg"), "#", id: unit.id, class: "featured_off", remote: true %>
              <% end %>
            </td>
          <% end %>
        <% end %>
        <td><%= unit.number %></td>
        <td><%= unit.avail_date.strftime("%a, %b %e") %></td>
        <td><%= unit.category.name %></td>
        <td><%= unit.building.name %></td>
        <td><%= unit.title %></td>
        <td><%= unit.bedrooms %></td>
        <td><%= unit.bathrooms %></td>
        <td><%= number_to_currency(unit.price) %></td>
        <td><%= unit.phoneNum %></td>
        <%# <td><%= unit.image ></td> %>
        <td><%= link_to 'More Information', unit %></td>
        <% if user_signed_in? %>
          <% if current_user.has_role? :admin %>
            <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
            <td><%= link_to 'Delete', unit, method: "delete", confirm: 'Are you sure?', remote: true, class: "delete_unit" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <%= link_to 'New Unit', new_unit_path, class: "button small success radius" %>
  <% end %>
<% end %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p>
  <strong>Unit Number:</strong>
  <%= @unit.number %>
</p>

<p>
  <strong>Availability Date:</strong>
  <%= @unit.avail_date.strftime("%A, %B %e %Y") %>
</p>

<p>
  <strong>Category:</strong>
  <%= @unit.category.name %>
</p>

<p>
  <strong>Building:</strong>
  <%= @unit.building.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @unit.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @unit.description %>
</p>

<p>
  <strong>Number of Bedrooms:</strong>
  <%= @unit.bedrooms %>
</p>

<p>
  <strong>Number of Bathrooms:</strong>
  <%= @unit.bathrooms %>
</p>

<p>
  <strong>Price Per Month:</strong>
  <%= number_to_currency(@unit.price) %>
</p>

<p>
  <strong>Contact Phone Number:</strong>
  <%= @unit.phoneNum %>
</p>

<% if @unit.link? %>
<p>
  <strong>Link:</strong>
  <%= link_to @unit.title, @unit.link %>
</p>
<% end %>

<% if @unit.image? %>
<p>
  <strong>Image:</strong><br/>
  <%= image_tag @unit.image_url(:main) if @unit.image? %>
</p>
<% end %>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>