config/routes.rb
require 'sidekiq/web'

Liveinbham::Application.routes.draw do
	root :to => "home#index"

	get "administrator/index", :as => "admin"
	devise_for :users, :controllers => {:registrations => "registrations"}

	resources :users
	resources :buildings
	resources :categories
	resources :zip_codes
	resources :units

	namespace :api, defaults: {format: 'json'} do
	    namespace :v1 do
	    	resources :units
	    	resources :categories
	    	get "featured", to: 'units#featured'
	    	get "viewer", to: 'units#viewer'
	    end
	end
	authenticate :user, lambda{ |u| u.has_role? :admin } do
		mount Sidekiq::Web, at: '/sidekiq'
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :units
	validates_presence_of :name, :catBegin, :catEnd
end

app/controllers/api/v1/categories_controller.rb
module Api
	module V1
		class CategoriesController < ApplicationController
			before_filter :restrict_access
			respond_to :json

			def index
				@categories = Category.all
				respond_with { @categories }
			end

		private
			def restrict_access
				api_key = ApiKey.find_by_access_token(params[:access_token])
				head :unauthorized unless api_key
			end
		    # Use callbacks to share common setup or constraints between actions.
		    def set_category
		      @category = Category.find(params[:id])
		    end

		    # Never trust parameters from the scary internet, only allow the white list through.
		    def category_params
		      params.require(:category).permit(:name, :catBegin, :catEnd)
		    end
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @categories = Category.all
  end

  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @category = Category.new
  end

  def edit
    authorize! :edit, @user, :message => 'Not authorized as an administrator.'
  end

  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destory, @user, :message => 'Not authorized as an administrator.'
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :catBegin, :catEnd)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :catBegin, label: "Category Begin Number" %>
    <%= f.input :catEnd, label: "Category End Number" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', admin_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category Begin Number</th>
      <th>Category End Number</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td><%= category.catBegin %></td>
        <td><%= category.catEnd %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: "button small success radius" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Category Begin Number:</strong>
  <%= @category.catBegin %>
</p>

<p>
  <strong>Category End Number:</strong>
  <%= @category.catEnd %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', admin_path %>